#!/usr/bin/env python


from sys import stderr
import os.path
from glob import glob
import re

here = os.path.dirname(os.path.abspath(__file__))


template_suffix = '.md'

goods = ['.py', '.java', '.cpp', '.md', '.json', 'testscript']
print('only loading files with ending', goods)

# replace
def get_replacements():
    for example in os.listdir(os.path.join(here, '..', 'examples')):
        base = os.path.join(here, '..', 'examples', example)
        if os.path.isdir(base):
            for pathname in sorted(glob(os.path.join(base, '*'))):
                if os.path.isfile(pathname) and any(pathname.endswith(x) for x in goods):
                    with open(pathname) as f:
                        yield re.compile(r'{{\s*' + os.path.join(example, os.path.basename(pathname)) + r'\s*}}'), f.read().strip('\n')


replacements = list(get_replacements())

def get_templates():
    for dirpath, dirnames, filenames in os.walk(here):
        for filename in filenames:
            if filename.endswith(template_suffix):
                base = filename[:-len(template_suffix)]
                rel_dir = os.path.relpath(dirpath, here)
                rel_loc = os.path.join(rel_dir, filename)
                if rel_loc.startswith('./'): rel_loc = rel_loc[2:]
                yield os.path.join(dirpath, filename), os.path.join(here, '..', 'docs', rel_dir, base + '.md'), rel_loc


for location, target, rel_loc in get_templates():
    print('COMPILING', location, 'TO', target)
    with open(location) as f:
        s = f.read()

    # replace
    for old, new in replacements:
        s = old.sub(new, s)

    def next_ref(s, pos):
        i = s.find('{{', pos)
        if i != -1:
            j = s.find('}}', i)
            if j != -1:
                return (i, j+2), j+2

    def find_refs(s):
        pos = 0
        while True:
            res = next_ref(s, pos)
            if not res: break
            (i, j), pos = res
            yield s[i: j]


    for found in find_refs(s):
        ref = repr(found)
        if len(ref) > 30*2+3: ref = ref[:30] + '...' + ref[-30:]
        print(f'WARNING: reference {ref} not found')

    with open(target, 'w') as f:
        print("<!-- NOTE TO CONTRIBUTORS: PLEASE DON'T EDIT THIS FILE. -->", file=f)
        print(f"<!-- Edit docs_src/{rel_loc} instead, then run './makedocs'. -->\n\n", file=f)
        f.write(s)

    # TODO possibly use a templating engine here instead of ad-hoc code
