#!/bin/bash

set -e

while IFS= read -rd '' file; do
    y=`"${@:2}" < $file`
    if [ -z "$y" ]; then
        printf "ERROR!!!! %s doesn't appear in any subtask\n" $file
        exit 1
    fi
    printf "%30s appears in the following subtasks: " $file
    for sub in $y; do
        printf "%s " $sub
    done
    echo
done < <(find $1 -print0 | sort -z -V)

echo SUBTASKS OK
