#!/bin/bash

set -e

mkdir -p input
mkdir -p output  
for x in input/input*.txt output/output*.txt; do
    [ -e $x ] && rm $x
done

idx=0
if ! [ -z $1 ]; then
    while IFS= read -rd '' src; do
        cp $src $(printf "input/input%02d.txt" $idx)       # input file 
        cp $src.a $(printf "output/output%02d.txt" $idx)   # output file 
        idx=$((idx+1))
    done < <(find $1/* -print0 | grep -z -v '\.a$' | sort -z -V)
fi

echo Converted $idx files
