#!/bin/bash

set -e

script_name=$0
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# prepare hackerrank folders
echo PREPARING FOLDERS
mkdir -p input
mkdir -p output  
for x in input/input*.txt output/output*.txt
do
    [ -e $x ] && rm $x
done

# create data set
echo GENERATING INPUT FILES
/usr/bin/python2 $__dir/_compile_testsets_to_bash.py $1 "$2" | bash
echo GENERATED $(find input/input*.txt | wc -l) FILES

# detect subtasks
subs=${@:4}
if [ -z "$subs" ]
then
    echo NO SUBTASKS LIST... NOT DETECTING SUBTASKS
else
    echo DETECTING SUBTASKS
    $__dir/all_files_subtasks "input/input*.txt" $__dir/subtasks_from_validator "$2" $subs
fi

# generate output
echo GENERATING OUTPUT FILES
$__dir/hr genout $3

echo DONE
