#!/bin/bash

set -e

testset="$1"
if [[ -z "$testset" ]]; then
    >&2 echo "ERROR (direct_to_hackerrank): The first argument must be the location of the testset script."  
    exit 1
fi

if [[ -z "$2" ]]; then
    >&2 echo "ERROR (direct_to_hackerrank): The second argument must be the validator command."  
    exit 1
fi

if [[ -z "$3" ]]; then
    >&2 echo "ERROR (direct_to_hackerrank): The thirds argument must be the solution command."  
    exit 1
fi

echo "PREPARING FOLDERS"
current="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p input output  
for x in input/input*.txt output/output*.txt; do
    [ -e $x ] && rm $x
done

# create data set
echo "GENERATING INPUT FILES"
/usr/bin/python2 $current/_compile_testsets_to_bash.py "$testset" "$2" | bash
echo "GENERATED $(find input/input*.txt | wc -l) FILES"

# detect subtasks
subs="$4"
if [[ -z "$subs" ]]; then
    echo "NO SUBTASKS LIST... NOT DETECTING SUBTASKS"
else
    echo "DETECTING SUBTASKS"
    $current/all_files_subtasks "input/input*.txt" $current/subtasks_from_validator $subs "$2"
fi

# generate output
echo "GENERATING OUTPUT FILES"
$current/hr genout "$3"

echo "DONE. ALL OK"
