#!/usr/bin/env python3

from io import StringIO
from subprocess import PIPE
from sys import stdin, stderr
import tempfile
import argparse

from kg.programs import *

parser = argparse.ArgumentParser(description='Run against the validator across multiple subtasks and print those which accept.')

parser.add_argument('subs', nargs='+', help='List of subtasks')
parser.add_argument('-c', '--command', nargs='+', help='validator command')

args = parser.parse_args()

prog = Program.from_args(None, args.command)

inp = stdin.read()
prog.do_compile()
for sub in args.subs:
    res = prog.do_run(sub, input=inp.encode('utf-8'), stderr=PIPE, stdout=PIPE, check=False)
    if res.returncode == 0:
        print(sub)
