#!/bin/bash

set -e

# check if some params are missing
subs="$1"
if [[ -z "$subs" ]]; then
    >&2 echo "ERROR (subtasks_from_validator): The first argument must be the subtask list, comma separated."
    exit 1
fi

if [[ -z "${@:2}" ]]; then
    >&2 echo "ERROR (subtasks_from_validator): The rest of the arguments must be the validator command."
    exit 1
fi

BASURA=/tmp/basura_delete_later_once_scripts_finish_running
cat > $BASURA # store input to temp file

for sub in $(echo "$subs" | sed "s/,/ /g"); do
    if ${@:2} $sub < $BASURA > ${BASURA}_vout 2> ${BASURA}_verr; then
        echo $sub
    fi
done


# remove kalat
for x in ${BASURA}{,_v{out,err}}; do
    [ -e $x ] && rm $x
done
